version: "3.9"

services:
  db:
    container_name: furnituredb
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: furnituredb
      MYSQL_ROOT_PASSWORD: coit
      MYSQL_ROOT_HOST: root
    expose:
      - '3306'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - local-net

  api:
    container_name: "furnitureapi"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - local-net
    depends_on:
      - db

networks:
  local-net:
    driver: bridge
