version: "3.9"

services:
  db:
    container_name: furniture_db
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: furniture_db
      MYSQL_USER: coit
      MYSQL_PASSWORD: coit
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - local-net

  api:
    container_name: "furniture_api"
    restart: always
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - local-net
    depends_on:
      - db

networks:
  local-net:
    driver: bridge
